services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd nextjs13-tailwindcss && npm run dev'
    ports:
      - 8888:3000
      - 3001:3001
    tty: true
